config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"

  resources :countings
  get "sessions/create"
  get "sessions/destroy"

  get "auth/:provider/callback", to: "sessions#create"
  get "auth/failure", to: redirect("/")
  get "signout", to: "sessions#destroy", as: "signout"

  resources :sessions, only: [:create, :destroy]
  get "sessions/login", to: "sessions#login"
  root to: "countings#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/counting.rb
# == Schema Information
#
# Table name: countings
#
#  id              :bigint           not null, primary key
#  amount          :float            default(0.0)
#  basic_currency  :string
#  duration        :integer
#  target_currency :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  user_id         :bigint
#
# Indexes
#
#  index_countings_on_user_id  (user_id)
#

class Counting < ApplicationRecord
  AVAILABLE_CURRENCIES = %i(
    AUD BGN BRL CAD
    CHF CNY CZK DKK
    EUR GBP HKD HRK
    HUF IDR ILS INR
    JPY KRW MXN MYR
    NOK NZD PHP PLN
    RON RUB SEK SGD
    THB TRY USD ZAR
  ).freeze

  belongs_to :user

  validates :amount, :basic_currency, :target_currency, :duration, presence: true
  validates :duration, numericality: { less_than_or_equal_to: 50,  only_integer: true }

  after_commit :save_rates

  def duration_in_days
    duration * 7
  end

  private

  def save_rates
    # TODO: check need or not
    SetHistoryRatesWorker.perform_async(duration_in_days)
  end
end

app/models/global_config.rb
# == Schema Information
#
# Table name: global_configs
#
#  id          :bigint           not null, primary key
#  latest_rate :json
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

# We can use this model for global variables that changed by admin or automatically
class GlobalConfig < ApplicationRecord
  def self.[](data)
    GlobalConfig.first[data]
  end

  def self.get_rates
    GlobalConfig.first&.latest_rate&.dig("rates") || {}
  end
end

app/models/rate_history.rb
# == Schema Information
#
# Table name: rate_histories
#
#  id         :bigint           not null, primary key
#  date       :date
#  value      :json
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class RateHistory < ApplicationRecord
  validates :date, :value, presence: true

  validates :date, uniqueness: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id               :bigint           not null, primary key
#  name             :string
#  oauth_expires_at :datetime
#  oauth_token      :string
#  provider         :string
#  uid              :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class User < ApplicationRecord
  has_many :countings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def authentication!
    redirect_to sessions_login_path if current_user.blank?
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/controllers/countings_controller.rb
class CountingsController < ApplicationController
  before_action :authentication!
  before_action :set_counting, only: %i(show edit update destroy)

  def index
    @countings = current_user.countings
  end

  def show
    @facade = CollectDataForShow.new(@counting)
  end

  def new
    @counting = Counting.new
  end

  def create
    @counting = current_user.countings.new(counting_params)
    return render :new unless @counting.save

    redirect_to @counting, notice: "Counting was successfully created."
  end

  def update
    return render :edit unless @counting.update(counting_params)

    redirect_to @counting, notice: "Counting was successfully updated."
  end

  def destroy
    @counting.destroy
    redirect_to countings_url, notice: "Counting was successfully destroyed."
  end

  private

  def set_counting
    @counting = current_user.countings.find(params[:id])
  end

  def counting_params
    params.require(:counting).permit(
      :basic_currency,
      :target_currency,
      :amount,
      :duration
    )
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    session[:user_id] = UserFromOmniauth.call(request.env["omniauth.auth"]).id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countings_helper.rb
module CountingsHelper
  def count_sum_by_rate(rate, amount)
    (rate * amount).round(2)
  end

  # profit/loss in comparison with latest_rate
  def profit_sum(latest_rate, rate, amount)
    count_sum_by_rate(latest_rate - rate, amount)
  end
end

app/views/countings/_form.html.erb
<%= simple_form_for counting do |form| %>
  <% if counting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(counting.errors.count, "error") %> prohibited this counting from being saved:</h2>

      <ul>
      <% counting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.input :amount, as: :integer %>
    <%= form.input :basic_currency, collection: Counting::AVAILABLE_CURRENCIES %>
    <%= form.input :target_currency, collection: Counting::AVAILABLE_CURRENCIES %>
    <%= form.input :duration, as: :integer, label: "Duration in weeks" %>
    <%= form.button :submit, class: "btn btn-success" %>
  </div>
<% end %>
<br>

app/views/countings/edit.html.erb
<h1>Editing Counting</h1>

<%= render "form", counting: @counting %>

<%= link_to "Show", @counting, class: "btn btn-info" %>
<%= link_to "Back", countings_path, class: "btn btn-secondary" %>

app/views/countings/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center">Your exchange rates for a currency pair</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Basic currency</th>
      <th scope="col">Target currency</th>
      <th scope="col">Amount</th>
      <th scope="col">Duration (in weeks)</th>
      <th scope="col">Show</th>
      <th scope="col">Edit</th>
      <th scope="col">Destroy</th>
    </tr>
  </thead>
  <tbody>
    <% @countings.each_with_index do |counting, index| %>
      <tr>
        <td scope="row"><%= index + 1%></td>
        <td><%= counting.basic_currency %></td>
        <td><%= counting.target_currency %></td>
        <td><%= counting.amount %></td>
        <td><%= counting.duration %></td>
        <td><%= link_to counting, class: "btn btn-info" do %><i class="fa fa-eye"></i><% end %></td>
        <td><%= link_to edit_counting_path(counting), class: "btn btn-warning" do %><i class="fa fa-pencil-square-o" aria-hidden="true"></i><% end %></td>
        <td><%= link_to counting, class: "btn btn-danger", method: :delete, data: { confirm: "Are you sure?" } do %><i class="fa fa-trash" aria-hidden="true"></i><% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "New Counting", new_counting_path, class: "btn btn-secondary" %>

app/views/countings/new.html.erb
<h1>New Counting</h1>

<%= render "form", counting: @counting %>

<%= link_to "Back", countings_path %>

app/views/countings/show.html.erb
<p id="notice"><%= notice %></p>
<br/>

<% if @facade.data_is_loading %>
  <h1>Data is loading. Please wait and update the page.</h1>
<% end %>

<table class="table table-dark">
  <caption>Basic info</caption>
  <thead>
    <tr>
      <th scope="col">Basic currency</th>
      <th scope="col">Target currency</th>
      <th scope="col">Duration</th>
      <th scope="col">Amount currency</th>
      <th scope="col">Rate now</th>
      <th scope="col">Latest amount</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th><%= @counting.basic_currency %></th>
      <td><%= @counting.target_currency %></td>
      <td><%= @counting.duration %></td>
      <td><%= @counting.amount %></td>
      <td><%= @facade.latest_rate.round(2) %></td>
      <td><%= count_sum_by_rate(@facade.latest_rate, @counting.amount) %></td>
    </tr>
  </tbody>
</table>

<div class="m-3">
  <%= link_to "Back", countings_path, class: "btn btn-secondary" %>
  <%= link_to "Edit", edit_counting_path(@counting), class: "btn btn-warning" %>
</div>

<hr>
<br><br><br><br>

<table class="table table-hover text-center">
  <caption>List of rates</caption>
  <thead>
    <tr>
      <th scope="col">Year</th>
      <th scope="col"># week in year</th>
      <th scope="col">Rate for a week</th>
      <th scope="col">The valuation of amount in base currency for the period of time</th>
      <th scope="col">Profit/loss in comparison with today"s rates</th>
    </tr>
  </thead>
  <tbody>
    <% @facade.table_data.each do |number_week, rate| %>
      <tr style = "background: #<%= number_week[:color] %>">
        <td scope="row"><%= number_week[:year] %></td>
        <td><%= number_week[:n_week] %></td>
        <td><%= rate.round(2) %></td>
        <td><%= count_sum_by_rate(rate, @counting.amount) %></td>
        <td><%= profit_sum(@facade.latest_rate, rate, @counting.amount) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= line_chart @facade.chart_data, min: nil %>

</br>
<div class="m-3">
  <%= link_to "Back", countings_path, class: "btn btn-secondary" %>
  <%= link_to "Edit", edit_counting_path(@counting), class: "btn btn-warning" %>
</div>

app/views/layouts/_top_menu.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Currency app</a>

  <div class="navbar-nav mr-auto text-center"></div>

  <div class="text-right">
    <% if current_user.present? %>
      <%= link_to signout_path, id: "sign_out" do %>
        <button class="btn btn-outline-danger">
          Sign out (<strong><%= current_user&.name %></strong>)
          <i class="fa fa-google-plus"></i>
        </button>
      <% end %>
    <% else %>
      <%= link_to "/auth/google_oauth2", id: "sign_in" do %>
        <button class="btn btn-outline-success">
          Sign In/Sign Up
          <i class="fa fa-google-plus"></i>
        </button>
      <% end %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Google Auth Example App</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render "layouts/top_menu" %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>